# Nixpacks configuration for Battle Bots: Arena Evolution
# This configuration optimizes static file serving for a real-time HTML5 game

[phases.setup]
# Install Node.js and necessary packages
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.install]
# Install project dependencies for the combined Node server (production-only)
cmds = ["npm ci --omit=dev"]

[phases.build]
# No build step needed - static files are ready to serve
cmds = ["echo 'No build required - static HTML5 game'"]

[start]
# Run combined HTTP static server + WebSocket signaling on the same PORT
cmd = "node server/full-server.js"

[staticAssets]
# Configure static asset handling
paths = [
  "index.html",
  "src/**/*",
  "test-game.html"
]

[variables]
# Environment variables (Railway will override PORT automatically)
NODE_ENV = "production"
